title: Cooking with Cale
description: A hacker, maker, greentech, and entrepreneur live-stream hosted by Cale McCollough.
author: Cale McCollough
logo: /static/img/avatar.png
github: https://github.com/CookingWithCale
linkedin: https://www.linkedin.com/in/calemccollough/
about: Open-source Cookbooks

baseurl: ""
url: "https://cookingwithcale.org"

allowsearch: true

disqus_shortname: cookingwithcale
google_analytics: UA-72862926-1

share:
  twitter_username: CookingWithCale
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
exclude: ['_site', 'node_modules', 'bug_report_template.md', 
  'code_of_conduct.md', 'contributing.md', 'feature_request_template.md', 
  'issue_template.md', 'pull_request_template.md', 'ReadMe.md', 'Roadmap.md', 
  'VideoTags.md']
